# ---------------------------------------------------------------------------------------------------------------------
# Service Layer — module: cloudsql
# A Postgres instance reachable only over private IP (no public IP), the
# application database, the application user, and the user's password stored in
# Secret Manager. The instance attaches to the app VPC through the PSA peering
# that the Foundation Layer network state established.
# ---------------------------------------------------------------------------------------------------------------------

# APIs (sqladmin, secretmanager) are enabled by the foundation project state,
# foundation/gcp-projects/yamato/dev/ — not here. The Service Layer assumes they
# are already on.

# ---------------------------------------------------------------------------------------------------------------------
# The Postgres instance — private IP only.
# ---------------------------------------------------------------------------------------------------------------------
#
# ip_configuration.ipv4_enabled = false means NO public IP is ever assigned;
# the only way in is over the VPC via the PSA peering. private_network points at
# the app VPC. enable_private_path_for_google_cloud_services lets other Google
# services reach the instance over the private path.
#
# availability_type ZONAL + db-f1-micro keep dev cheap. backups are on (you want
# them even in dev); point-in-time recovery is off (it adds WAL-archival cost and
# dev rarely needs sub-backup-granularity restore).
resource "google_sql_database_instance" "this" {
  project          = var.project_id
  name             = var.instance_name
  region           = var.region
  database_version = var.database_version

  deletion_protection = var.deletion_protection

  settings {
    tier              = var.tier
    edition           = var.edition
    availability_type = var.availability_type
    disk_type         = var.disk_type
    disk_size         = var.disk_size_gb
    disk_autoresize   = true
    user_labels       = var.labels

    ip_configuration {
      ipv4_enabled                                  = false
      private_network                               = var.network_id
      enable_private_path_for_google_cloud_services = true
    }

    backup_configuration {
      enabled                        = true
      start_time                     = var.backup_start_time
      point_in_time_recovery_enabled = false
      backup_retention_settings {
        retained_backups = 7
      }
    }
  }
}

# ---------------------------------------------------------------------------------------------------------------------
# The application database.
# ---------------------------------------------------------------------------------------------------------------------
resource "google_sql_database" "this" {
  project  = var.project_id
  name     = var.database_name
  instance = google_sql_database_instance.this.name
}

# ---------------------------------------------------------------------------------------------------------------------
# The application user + its generated password.
# ---------------------------------------------------------------------------------------------------------------------
#
# The password is generated by Terraform and never typed by a human. It lands in
# Secret Manager (below); the Cloud Run state grants its runtime SA read access
# to that secret. override_special trims the character set to symbols that are
# safe in a Postgres connection string / DSN without URL-encoding surprises.
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%*()-_=+"
}

resource "google_sql_user" "app" {
  project  = var.project_id
  name     = var.db_user
  instance = google_sql_database_instance.this.name
  password = random_password.db.result
}

# ---------------------------------------------------------------------------------------------------------------------
# Secret Manager — the DB password.
# ---------------------------------------------------------------------------------------------------------------------
#
# Automatic replication (Google picks regions) is fine for a dev secret. The
# secret container is created here; the actual password value is a secret
# version. Consumers (Cloud Run) reference this secret by ID and are granted
# accessor in their own state, so each state owns its own IAM.
resource "google_secret_manager_secret" "db_password" {
  project   = var.project_id
  secret_id = var.password_secret_id

  labels = var.labels

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}
